### ISSUE TITLE
Assertion '__builtin_expect(__n < this->size(), true)' failed when starting vdrift

### ISSUE THREAD

**Issue by ppalaga** [VDrift/vdrift#163]
`vdrift` crashes on start given the following error message:

```
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

This happens with all of the following binaries:

1. freshly built from master a5cc505 on Fedora 28
2. from vdrift-20141020-14.fc29.x86_64.rpm on Fedora 29 
3. from vdrift-20141020-13.fc28.x86_64 on Fedora 28

**Comment by logzero** [comment]
Might be the same issue as described here:
https://bugzilla.redhat.com/show_bug.cgi?id=1573253

> From googling, it seems there are some issues _GLIBCXX_ASSERTIONS versus overly aggressive gcc 8 optimizations, using the C++11 data() method sidesteps that.

**Comment by logzero** [comment]
I've pushed some changes into master, would be great if you could test them.

**Comment by ppalaga** [comment]
Thanks for your quick response, @logzero and for the fix. I rebuilded and I am getting a different error message:

```
ERROR: Failed to load "freesans.png" from:
       /home/ppalaga/.vdrift/skins/simple/fonts
       /usr/local/share/games/vdrift/data/skins/simple/fonts
       /usr/local/share/games/vdrift/data/carparts
       /usr/local/share/games/vdrift/data/trackparts
ERROR: Can't find font information file: /usr/local/share/games/vdrift/data/skins/simple/fonts/freesans.txt
ERROR: Error loading fonts
```

After googling a bit, I tried 

```
# data dir installed by RPM.
export VDRIFT_DATA_DIRECTORY=/usr/share/vdrift
./vdrift
```

And I got yet another error

```
ERROR: .engine.displacement not found.
ERROR: Failed to load physics for car: XS/XS
vdrift: src/gui/gui.cpp:557: GuiOption& Gui::GetOption(const string&): Assertion `it != options.end()' failed.
Aborted (core dumped)
```

Any ideas what I should try?

**Comment by logzero** [comment]
That is weird. Can you check if data/cars/XS.XS.car has displacement set:
[engine]
position = 0.0, 0.9, -0.3
mass = 140.0
displacement = 2.0E-3
...

**Comment by ppalaga** [comment]
Yes, when I added displacement, other param was missing. So I looked around where to get the current data. It looks like it resides under https://svn.code.sf.net/p/vdrift/code/ . Indeed after checking out from there, the game starts. Thanks for your assistance, @logzero !

**Comment by Mailaender** [comment]
I just cited the console output. I am using `vdrift-2014-10-20` from SourceForge.

**Comment by logzero** [comment]
What is the log.txt output? It should be in .local/share/VDrift/

Also if possible you could try debugging. Do a debug build and gdb -ex run ./vdrift

**Comment by logzero** [comment]
After Video card info you should get something like:

INFO: Loading data/shaders/gl3/deferred.conf...
INFO: Loaded data/shaders/gl3/deferred.conf

So it must be crashing trying to init the graphics system. There are numerous places where vectors are used. Without a stack trace it would be hard to guess which one has the out of bounds access and why.

One simple thing you could try is to delete startingup.txt and VDrift.config. It should use the default gl3 system instead of the gl2 failsafe on a restart. Check if the log.txt is any different.

**Comment by flamming-python** [comment]
Same bug

But the graphics card initializes successfully in my case

Thoughts?

```
INFO: Multi-processor system detected.  Run with -multithreaded argument to enable multithreading (EXPERIMENTAL).
INFO: Starting VDrift: 2024-01-08-full, Revision: Unversioned directory, O/S: Unix
INFO: Home directory: /home/python
INFO: Settings file: /home/python/.vdrift/VDrift.config (does not exist, will be created)
INFO: Data directory: /usr/share/vdrift/
DATA_DIR: /usr/share/vdrift/
INFO: Temporary directory: /home/python/.vdrift/tmp
INFO: Log file: /home/python/.vdrift/log.txt
ERROR: Failed to load /home/python/.vdrift/VDrift.config
INFO: Request OpenGL 3.3 Core Profile context.
INFO: Disabling antialiasing
INFO: Disabling vertical synchronization.
INFO: Video card information:
GL Vendor: NVIDIA Corporation
GL Renderer: GeForce GT 525M/PCIe/SSE2
GL Version: 3.3.0 NVIDIA 390.157
Texture units: 32
Maximum texture size: 16384
INFO: Loading /usr/share/vdrift//shaders/gl3/deferred.conf...
INFO: Loaded /usr/share/vdrift//shaders/gl3/deferred.conf
INFO: GL3 initialization successful
INFO: 0 joysticks found.
INFO: Loading car controls from: /home/python/.vdrift/controls.config
INFO: Failed to load car controls file /home/python/.vdrift/controls.config
INFO: Car control file /home/python/.vdrift/controls.config doesn't exist; using defaults
INFO: Update status file /home/python/.vdrift/updates.config will be created
INFO: Update status file /home/python/.vdrift/updates.config will be created
INFO: Sound initialization information:
INFO: Obtained audio device:
Frequency: 44100
Format: 32784
Bits per sample: 16
Channels: 2
Silence: 0
Samples: 2048
Size: 8192
Sound initialization successful
INFO: Loaded fonts successfully
/usr/include/c++/13.2.1/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'vdrift' terminated by signal SIGABRT (Abort)

```

**Comment by logzero** [comment]
As long as I can't replicate the issue, it's rather difficult. As I mentioned, a stack backtrace would be nice.

std::vector<float> is used by meshes, the particle system, car inputs and specs. The latter three shouldn't have out of bounds accesses. With meshes, corrupt indices could lead to out of bounds accesses. But that would mean faulty data being loaded by the game.

But that is just speculation.

**Comment by flamming-python** [comment]
The backtrace

```
/usr/include/c++/13.2.1/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Thread 1 "vdrift" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) backtrace
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
at pthread_kill.c:44
#1  0x00007ffff74ac8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff745c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff74444b8 in __GI_abort () at abort.c:79
#4  0x00007ffff76dd3b2 in std::__glibcxx_assert_fail (
file=file@entry=0x555555796e50 "/usr/include/c++/13.2.1/bits/stl_vector.h", line=line@entry=1125,
function=function@entry=0x555555797208 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]", condition=condition@entry=0x55555578f307 "__n < this->size()")
at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
#5  0x00005555556a7ba0 in std::vector<float, std::allocator<float> >::operator[] (this=<optimized out>,
__n=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_vector.h:1123
#6  std::vector<float, std::allocator<float> >::operator[] (this=0x555555d1c0f0, __n=<optimized out>)
at /usr/include/c++/13.2.1/bits/stl_vector.h:1123
#7  VertexArray::SetNormals (this=this@entry=0x555555d1c0c0, array=array@entry=0x0, count=count@entry=0,
offset=0) at src/graphics/vertexarray.cpp:146
#8  0x00005555556a7e5b in VertexArray::Add (this=this@entry=0x555555d1c0c0,
newfaces=newfaces@entry=0x7ffffffef800, newfacecount=newfacecount@entry=6,
newvert=newvert@entry=0x7ffffffef840, newvertcount=newvertcount@entry=12,
newtco=newtco@entry=0x7ffffffef820, newtcocount=8, newnorm=0x0, newnormcount=0, newcol=0x0,
newcolcount=0) at src/graphics/vertexarray.cpp:196
#9  0x0000555555668415 in GraphicsGL2::GraphicsGL2 (this=this@entry=0x555555d1bb80)
at src/graphics/graphics_gl2.cpp:269
#10 0x00005555555fe844 in Game::InitCoreSubsystems (this=this@entry=0x7fffffff08e0) at src/game.cpp:401
#11 0x000055555560ff6c in Game::Start (this=0x7fffffff08e0, args=...) at src/game.cpp:162
#12 0x000055555557fb7a in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:71
```

**Comment by logzero** [comment]
Not sure what is happening. It seems to trip over accessing an empty vector at index 0. But it shouldn't get that far in the first place, as there is an early out if count is 0. Compiler trying to be clever?

What is your gcc version?
